# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 280, 400, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.menuYoutubeDownloaderButton = QtWidgets.QPushButton(self.frame)
        self.menuYoutubeDownloaderButton.setGeometry(QtCore.QRect(50, 30, 300, 40))
        self.menuYoutubeDownloaderButton.setObjectName("menuYoutubeDownloaderButton")
        self.menuMetadataChangerButton = QtWidgets.QPushButton(self.frame)
        self.menuMetadataChangerButton.setGeometry(QtCore.QRect(50, 80, 300, 40))
        self.menuMetadataChangerButton.setObjectName("menuMetadataChangerButton")
        self.menuSongCutterButton = QtWidgets.QPushButton(self.frame)
        self.menuSongCutterButton.setGeometry(QtCore.QRect(50, 130, 300, 40))
        self.menuSongCutterButton.setObjectName("menuSongCutterButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 500, 308, 94))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.menuFolderBrowserButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.menuFolderBrowserButton.setObjectName("menuFolderBrowserButton")
        self.gridLayout.addWidget(self.menuFolderBrowserButton, 0, 2, 1, 1)
        self.menuFolderBrowserLine = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.menuFolderBrowserLine.setObjectName("menuFolderBrowserLine")
        self.gridLayout.addWidget(self.menuFolderBrowserLine, 0, 1, 1, 1)
        self.menuFolderBrowserDefault = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.menuFolderBrowserDefault.setObjectName("menuFolderBrowserDefault")
        self.gridLayout.addWidget(self.menuFolderBrowserDefault, 0, 3, 1, 1)
        self.menuOpenFolderButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.menuOpenFolderButton.setObjectName("menuOpenFolderButton")
        self.gridLayout.addWidget(self.menuOpenFolderButton, 1, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 21, 301, 231))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ultimate Music Handler"))
        self.menuYoutubeDownloaderButton.setText(_translate("MainWindow", "Youtube Downloader"))
        self.menuMetadataChangerButton.setText(_translate("MainWindow", "Metadata Changer"))
        self.menuSongCutterButton.setText(_translate("MainWindow", "Song Cutter"))
        self.label_3.setText(_translate("MainWindow", "Open Folder"))
        self.label.setText(_translate("MainWindow", "Folder"))
        self.menuFolderBrowserButton.setText(_translate("MainWindow", "Browse"))
        self.menuFolderBrowserDefault.setText(_translate("MainWindow", "Default"))
        self.menuOpenFolderButton.setText(_translate("MainWindow", "Open"))
