# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/mdc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 20, 341, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 350, 341, 100))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.songUrlLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.songUrlLabel.setObjectName("songUrlLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.songUrlLabel)
        self.songNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.songNameLabel.setObjectName("songNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.songNameLabel)
        self.metadataArtist = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.metadataArtist.setObjectName("metadataArtist")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.metadataArtist)
        self.metadataName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.metadataName.setObjectName("metadataName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.metadataName)
        self.albumLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.albumLabel.setObjectName("albumLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.albumLabel)
        self.metadataAlbum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.metadataAlbum.setObjectName("metadataAlbum")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.metadataAlbum)
        self.coverImageLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.coverImageLabel.setObjectName("coverImageLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.coverImageLabel)
        self.metadataCoverCheck = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.metadataCoverCheck.setText("")
        self.metadataCoverCheck.setObjectName("metadataCoverCheck")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.metadataCoverCheck)
        self.metadataChangeButton = QtWidgets.QPushButton(self.centralwidget)
        self.metadataChangeButton.setGeometry(QtCore.QRect(140, 460, 101, 41))
        self.metadataChangeButton.setObjectName("metadataChangeButton")
        self.metadataMenuButton = QtWidgets.QPushButton(self.centralwidget)
        self.metadataMenuButton.setGeometry(QtCore.QRect(140, 560, 101, 31))
        self.metadataMenuButton.setObjectName("metadataMenuButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 290, 81, 16))
        self.label_6.setObjectName("label_6")
        self.metadataSelectedSong = QtWidgets.QLabel(self.centralwidget)
        self.metadataSelectedSong.setGeometry(QtCore.QRect(110, 290, 261, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.metadataSelectedSong.setFont(font)
        self.metadataSelectedSong.setObjectName("metadataSelectedSong")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 530, 199, 21))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.metadataResult = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.metadataResult.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.metadataResult.setFont(font)
        self.metadataResult.setStyleSheet("color: green;")
        self.metadataResult.setText("")
        self.metadataResult.setObjectName("metadataResult")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.metadataResult)
        self.metadataList = QtWidgets.QListWidget(self.centralwidget)
        self.metadataList.setGeometry(QtCore.QRect(30, 80, 341, 201))
        self.metadataList.setObjectName("metadataList")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Metadata Changer"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Metadata Changer</span></p></body></html>"))
        self.songUrlLabel.setText(_translate("MainWindow", "Name"))
        self.songNameLabel.setText(_translate("MainWindow", "Artist"))
        self.albumLabel.setText(_translate("MainWindow", "Album"))
        self.coverImageLabel.setText(_translate("MainWindow", "Cover Image?"))
        self.metadataChangeButton.setText(_translate("MainWindow", "Change"))
        self.metadataMenuButton.setText(_translate("MainWindow", "Menu"))
        self.label_6.setText(_translate("MainWindow", "Selected song:"))
        self.metadataSelectedSong.setText(_translate("MainWindow", "Ashes of Dreams"))
        self.label.setText(_translate("MainWindow", "Result:"))
