# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/ytd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 190, 351, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.songUrlLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.songUrlLabel.setObjectName("songUrlLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.songUrlLabel)
        self.songNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.songNameLabel.setObjectName("songNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.songNameLabel)
        self.youtubeSongName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.youtubeSongName.setObjectName("youtubeSongName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.youtubeSongName)
        self.youtubeSongUrl = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.youtubeSongUrl.setObjectName("youtubeSongUrl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.youtubeSongUrl)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(25, 90, 341, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.youtubeDownloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.youtubeDownloadButton.setGeometry(QtCore.QRect(140, 260, 101, 41))
        self.youtubeDownloadButton.setObjectName("youtubeDownloadButton")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 530, 199, 21))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.youtubeResult = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.youtubeResult.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.youtubeResult.setFont(font)
        self.youtubeResult.setStyleSheet("color: green;")
        self.youtubeResult.setText("")
        self.youtubeResult.setObjectName("youtubeResult")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.youtubeResult)
        self.youtubeMenuButton = QtWidgets.QPushButton(self.centralwidget)
        self.youtubeMenuButton.setGeometry(QtCore.QRect(140, 560, 101, 31))
        self.youtubeMenuButton.setObjectName("youtubeMenuButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Downloader"))
        self.songUrlLabel.setText(_translate("MainWindow", "Song URL"))
        self.songNameLabel.setText(_translate("MainWindow", "Name (optional)"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Youtube Downloader</span></p></body></html>"))
        self.youtubeDownloadButton.setText(_translate("MainWindow", "Download"))
        self.label.setText(_translate("MainWindow", "Result:"))
        self.youtubeMenuButton.setText(_translate("MainWindow", "Menu"))
